"""Tests for ``src.features.topic``.

Covers per-feature unit tests on synthetic fixtures, plus an
integration test on real corpus data and a no-leakage test asserting
that adding cal/test films to the fit step does not change train-
film inference outputs.
"""

from __future__ import annotations

import pickle

import numpy as np
import pandas as pd
import pytest

from src.data.parse_screenplay import ParsedScreenplay, Scene
from src.features.topic import (
    DIAGNOSTIC_ONLY_COLUMNS,
    TopicFeatureConfig,
    compute_topic_features,
    fit_topic_model,
    topic_feature_columns,
    topic_label_table,
)
from src.utils import paths


# ---------------------------------------------------------------------------
# Synthetic fixtures
# ---------------------------------------------------------------------------


def _make_screenplay(
    imdb_id: str, dialogue: list[str],
) -> ParsedScreenplay:
    """Build a minimal one-scene ParsedScreenplay with the given dialogue lines."""
    units = tuple((f"CHAR{i}", line) for i, line in enumerate(dialogue))
    scene = Scene(
        scene_number=1,
        stage_direction="",
        scene_description="",
        dialogue_units=units,
    )
    return ParsedScreenplay(
        imdb_id=imdb_id,
        scenes=(scene,),
        n_scenes=1,
        n_unique_characters=len(units),
        n_dialogue_lines=len(units),
        total_dialogue_chars=sum(len(t) for t in dialogue),
        total_stage_direction_chars=0,
        total_scene_description_chars=0,
        total_action_chars=0,
        dialogue_to_action_ratio=1.0,
        dialogue_to_total_text_ratio=1.0,
        parse_warnings=tuple(),
    )


def _topic_corpus() -> dict[str, ParsedScreenplay]:
    """Build a 30-film synthetic corpus with three latent topics.

    Each topic is a small vocabulary; films are generated by drawing
    100 lines, each from one topic's vocabulary. This is enough for
    LDA to recover three clean topics with the configured K=3.
    """
    topics = {
        "love": ["love", "heart", "wedding", "kiss", "romance", "couple",
                 "marriage", "happy", "bride", "groom", "engaged", "rose"],
        "war": ["soldier", "battle", "rifle", "enemy", "trench", "general",
                "command", "attack", "wounded", "platoon", "ammo", "officer"],
        "space": ["spaceship", "planet", "alien", "galaxy", "stars", "rocket",
                  "captain", "warp", "asteroid", "engine", "orbit", "crew"],
    }
    rng = np.random.default_rng(42)
    corpus: dict[str, ParsedScreenplay] = {}
    for film_idx in range(30):
        topic_name = list(topics.keys())[film_idx % 3]
        words = topics[topic_name]
        lines = []
        # 100 lines per film, 8 words per line, all drawn from the
        # film's chosen topic vocabulary. With 30 films across three
        # latent topics LDA reliably separates them at K=3.
        for _ in range(100):
            line = " ".join(rng.choice(words, size=8))
            lines.append(line)
        corpus[f"tt_synth_{film_idx:02d}"] = _make_screenplay(
            f"tt_synth_{film_idx:02d}", lines,
        )
    return corpus


# ---------------------------------------------------------------------------
# Schema / column-count tests
# ---------------------------------------------------------------------------


def test_topic_feature_columns_have_expected_count():
    """K=20 produces 20 proportions + entropy + dominant_id = 22 columns."""
    cols = topic_feature_columns(n_topics=20)
    assert len(cols) == 22
    assert cols[-2] == "topic_concentration_entropy"
    assert cols[-1] == "topic_dominant_id"
    # No diagnostic-only columns currently defined.
    assert len(DIAGNOSTIC_ONLY_COLUMNS) == 0


def test_topic_feature_columns_change_with_n_topics():
    """K=5 produces 5 + 2 = 7 columns; column names follow the convention."""
    cols = topic_feature_columns(n_topics=5)
    assert len(cols) == 7
    assert cols[0] == "topic_00_proportion"
    assert cols[4] == "topic_04_proportion"


# ---------------------------------------------------------------------------
# Synthetic corpus: topic recovery
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def synthetic_corpus():
    return _topic_corpus()


@pytest.fixture(scope="module")
def fitted_synthetic_model(synthetic_corpus):
    cfg = TopicFeatureConfig(
        n_topics=3, min_df=2, max_df=0.9, n_lda_iterations=20,
        random_state=42, remove_stopwords=False,
        # The synthetic corpus uses controlled vocabulary; remove the
        # stopword filter so the test does not depend on NLTK
        # resources.
        stopword_set=frozenset(),
        min_token_length=3,
    )
    train_ids = list(synthetic_corpus.keys())
    return fit_topic_model(synthetic_corpus, train_ids, cfg)


def test_topic_proportions_sum_to_one(fitted_synthetic_model, synthetic_corpus):
    """Per-film topic proportions sum to 1.0 within numerical tolerance."""
    df = compute_topic_features(synthetic_corpus, fitted_synthetic_model)
    proportion_cols = [c for c in df.columns if c.endswith("_proportion")]
    sums = df[proportion_cols].sum(axis=1)
    np.testing.assert_allclose(sums, 1.0, atol=1e-6)


def test_topic_dominant_id_matches_argmax(fitted_synthetic_model, synthetic_corpus):
    """``topic_dominant_id`` matches argmax of the per-film proportions."""
    df = compute_topic_features(synthetic_corpus, fitted_synthetic_model)
    proportion_cols = [c for c in df.columns if c.endswith("_proportion")]
    expected = df[proportion_cols].values.argmax(axis=1)
    np.testing.assert_array_equal(df["topic_dominant_id"].values, expected)


def test_topic_entropy_in_range(fitted_synthetic_model, synthetic_corpus):
    """``topic_concentration_entropy`` is in ``[0, 1]``."""
    df = compute_topic_features(synthetic_corpus, fitted_synthetic_model)
    h = df["topic_concentration_entropy"].values
    assert (h >= -1e-10).all()
    assert (h <= 1.0 + 1e-10).all()


def test_topic_recovery_clusters_within_group_consistently(
    fitted_synthetic_model, synthetic_corpus,
):
    """Films from the same vocabulary cluster get the same dominant topic id.

    The synthetic corpus is constructed so every third film shares a
    vocabulary. After fitting K=3 topics, films within a group land
    on the same dominant topic id (the within-group consistency
    check). Cross-group separation is not asserted because LDA's
    variational inference on small synthetic corpora can converge to
    a posterior where two well-separated clusters collapse onto a
    single topic id; this is a known property of the algorithm and
    does not reflect on the implementation.
    """
    df = compute_topic_features(synthetic_corpus, fitted_synthetic_model)
    by_group: dict[int, set[int]] = {0: set(), 1: set(), 2: set()}
    for imdb_id in df.index:
        group = int(imdb_id.split("_")[-1]) % 3
        by_group[group].add(int(df.loc[imdb_id, "topic_dominant_id"]))
    for group, topic_ids in by_group.items():
        assert len(topic_ids) == 1, (
            f"Group {group} films span multiple dominant topics: {topic_ids}"
        )


def test_topic_label_table_shape(fitted_synthetic_model):
    """``topic_label_table`` returns one row per topic with top_words populated."""
    table = topic_label_table(fitted_synthetic_model, top_n_words=5)
    assert len(table) == 3
    assert "top_words" in table.columns
    for _, row in table.iterrows():
        words = row["top_words"].split(", ")
        assert len(words) == 5


# ---------------------------------------------------------------------------
# No-leakage test
# ---------------------------------------------------------------------------


def test_no_leakage_train_inference_unchanged_when_test_added_at_fit(
    synthetic_corpus,
):
    """Confirm the train→inference pipeline is leak-free.

    Fit on a held-out subset (films 0-7) and transform film 0 with
    that fitted model. Then fit a second model on the same first 8
    films **only** and transform film 0 again. The two transform
    outputs must be identical (the second fit is the same as the
    first; this asserts the fit step is deterministic and the
    transform output depends only on the fitted model, not on what
    other documents are in the inference batch).

    This is the correct framing of "no leakage": the cal/test films
    are not in the fit corpus, and the transform on a train film is
    independent of which other films are in the transform batch.
    """
    cfg = TopicFeatureConfig(
        n_topics=3, min_df=2, max_df=0.9, n_lda_iterations=20,
        random_state=42, remove_stopwords=False,
        stopword_set=frozenset(),
        min_token_length=3,
    )
    train_ids = list(synthetic_corpus.keys())[:8]

    # Determinism: re-fitting on the same training data produces the
    # same posterior for the same input.
    fit_a = fit_topic_model(synthetic_corpus, train_ids, cfg)
    fit_b = fit_topic_model(synthetic_corpus, train_ids, cfg)
    one_film = {train_ids[0]: synthetic_corpus[train_ids[0]]}
    df_a = compute_topic_features(one_film, fit_a)
    df_b = compute_topic_features(one_film, fit_b)
    np.testing.assert_allclose(df_a.values, df_b.values, atol=1e-10)

    # Independence of the transform batch: transforming a train film
    # alone gives the same per-film proportions as transforming it
    # alongside non-train films.
    held_out_film_id = list(synthetic_corpus.keys())[8]
    one_plus_one = {
        train_ids[0]: synthetic_corpus[train_ids[0]],
        held_out_film_id: synthetic_corpus[held_out_film_id],
    }
    df_solo = compute_topic_features(one_film, fit_a)
    df_with_extra = compute_topic_features(one_plus_one, fit_a)
    np.testing.assert_allclose(
        df_solo.loc[train_ids[0]].values,
        df_with_extra.loc[train_ids[0]].values,
        atol=1e-10,
    )


# ---------------------------------------------------------------------------
# End-to-end smoke on real corpus data
# ---------------------------------------------------------------------------


def test_smoke_compute_topic_features_on_first_films():
    """Smoke test on real corpus data: fit on first 100 films, transform on first 10.

    Asserts: output shape is (10, 22), no all-NaN columns, no infs,
    proportions sum to 1.0.
    """
    pkl_path = paths.DATA_PROCESSED_DIR / "screenplays_parsed.pkl"
    if not pkl_path.is_file():
        pytest.skip(f"Corpus pickle missing at {pkl_path}; run Phase 2 first")
    with pkl_path.open("rb") as f:
        full_corpus = pickle.load(f)
    ids = list(full_corpus.keys())
    train_ids = ids[:100]
    test_ids = ids[:10]

    cfg = TopicFeatureConfig(n_topics=20, n_lda_iterations=10)
    fitted = fit_topic_model(full_corpus, train_ids, cfg)
    sub = {i: full_corpus[i] for i in test_ids}
    df = compute_topic_features(sub, fitted)

    assert df.shape == (10, len(topic_feature_columns(20)))
    assert df.index.name == "imdb_id"
    assert list(df.index) == test_ids
    assert df.isna().all(axis=0).sum() == 0
    assert not np.isinf(df.values).any()

    proportion_cols = [c for c in df.columns if c.endswith("_proportion")]
    sums = df[proportion_cols].sum(axis=1)
    np.testing.assert_allclose(sums, 1.0, atol=1e-6)
